spring.application.name=discordbot
spring.config.import=optional:file:envs/${APP_ENV:local}.properties

service.spreadsheet.sheet-name=reg
service.spreadsheet.key-file-name=table-key.json

service.birthdays.enabled=false
service.birthdays.sheet-name=birthday
service.birthdays.range=A:B
service.birthdays.skip-header=false
service.birthdays.look-ahead-days=3
service.birthdays.cron=0 0 15 * * *
service.birthdays.zone=Europe/Kiev
service.birthdays.notify-when-empty=false

service.commands.register.enabled=true
service.commands.valentine.enabled=true
service.commands.mines.enabled=true

service.twitch.enabled=false
service.twitch.check-interval-ms=10000
service.twitch.notify-on-startup=true

##
service.twitch.streamers[0].login=burni228
service.twitch.streamers[0].discord-channel-id=1531419232238047312
service.twitch.streamers[0].message-template=бирни даун запустил тестовый стрим
service.twitch.streamers[0].embed-enabled=true

service.twitch.streamers[1].login=liqnelyn
service.twitch.streamers[1].discord-channel-id=1531419232238047312
service.twitch.streamers[1].message-template=медиамолекула опять запустила
service.twitch.streamers[1].embed-enabled=true

service.twitch.streamers[2].login=the_ruined_kaito
service.twitch.streamers[2].discord-channel-id=1531419232238047312
service.twitch.streamers[2].message-template=топ1 фембой ру сервера онлайн
service.twitch.streamers[2].embed-enabled=true

service.twitch.streamers[3].login=jrachelxd
service.twitch.streamers[3].discord-channel-id=1531419232238047312
service.twitch.streamers[3].message-template=никитка добряш мескаль онлайн без смс и регистрации
service.twitch.streamers[3].embed-enabled=true

service.twitch.streamers[4].login=melover
service.twitch.streamers[4].discord-channel-id=1531419232238047312
service.twitch.streamers[4].message-template=петр андреевич онлайн!
service.twitch.streamers[4].embed-enabled=true

service.twitch.streamers[5].login=ayayakavich
service.twitch.streamers[5].discord-channel-id=1531419232238047312
service.twitch.streamers[5].message-template=аяаяка из аяаянии стримит аяаятницу
service.twitch.streamers[5].embed-enabled=true

service.twitch.streamers[6].login=wilsolol
service.twitch.streamers[6].discord-channel-id=1531419232238047312
service.twitch.streamers[6].message-template=олежа вилсо гапает
service.twitch.streamers[6].embed-enabled=true

service.twitch.streamers[7].login=luckerlfl
service.twitch.streamers[7].discord-channel-id=1531419232238047312
service.twitch.streamers[7].message-template=кирюша трезвеет от этих чатерсов
service.twitch.streamers[7].embed-enabled=true

service.twitch.streamers[8].login=chifffa
service.twitch.streamers[8].discord-channel-id=1531419232238047312
service.twitch.streamers[8].message-template=эгоист манипулятор вадимка показывает разницу
service.twitch.streamers[8].embed-enabled=true

service.twitch.streamers[9].login=ratata_ratl9
service.twitch.streamers[9].discord-channel-id=1531419232238047312
service.twitch.streamers[9].message-template=даня стримит о свершилось
service.twitch.streamers[9].embed-enabled=true

service.twitch.streamers[10].login=lal1k32
service.twitch.streamers[10].discord-channel-id=1531419232238047312
service.twitch.streamers[10].message-template=маленький нетроганный фембойчик
service.twitch.streamers[10].embed-enabled=true

service.twitch.streamers[11].login=bogww
service.twitch.streamers[11].discord-channel-id=1531419232238047312
service.twitch.streamers[11].message-template=деда на цепь
service.twitch.streamers[11].embed-enabled=true

service.twitch.streamers[12].login=yonqar
service.twitch.streamers[12].discord-channel-id=1531419232238047312
service.twitch.streamers[12].message-template=лучшая отп юми мурлычет за киллы в прямом эфире
service.twitch.streamers[12].embed-enabled=true